global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "jmx-exporter"
    static_configs:
      - targets: ["kafka-1:7071"]
    metrics_path: "/metrics"
    scrape_interval: 15s
